# Generated by Django 5.1.4 on 2026-05-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('source_text', models.TextField(blank=True)),
                ('target_text', models.TextField(blank=True)),
                ('source_lang', models.CharField(default='auto', max_length=24)),
                ('target_lang', models.CharField(default='ta', max_length=24)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
